name: "Bug Report (EN)"
description: "Report a reproducible bug with required versions, setup method, and logs."
title: "[Bug] "
labels:
  - type:bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide complete details so maintainers can reproduce quickly.

  - type: checkboxes
    id: precheck_search
    attributes:
      label: Pre-check
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true

  - type: dropdown
    id: regression
    attributes:
      label: Regression?
      options:
        - "Yes (worked before, broken now)"
        - "No"
        - "Not sure"
    validations:
      required: true

  - type: input
    id: openclaw_version
    attributes:
      label: OpenClaw Version
      description: "Example: output of `openclaw --version`"
      placeholder: "e.g. 2026.2.13"
    validations:
      required: true

  - type: input
    id: plugin_version
    attributes:
      label: Feishu Plugin Version
      description: "Example: output from `openclaw plugins list`"
      placeholder: "e.g. @m1heng-clawd/feishu 0.1.3"
    validations:
      required: true

  - type: dropdown
    id: install_source
    attributes:
      label: Plugin Install Source
      options:
        - "npm package (openclaw plugins install @m1heng-clawd/feishu)"
        - "local path (-l /path/to/clawdbot-feishu)"
        - "local tarball (.tgz)"
        - "other"
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to Reproduce
      description: "Use numbered steps and include trigger actions."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs (Optional)
      description: "If available, include startup logs and logs around the failure window."
      render: shell
      placeholder: |
        [startup]
        ...

        [when reproducing]
        ...

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: "OS, Node.js version, deployment mode (local/docker/server)."
      placeholder: "macOS 14.7, Node v22.x, local daemon"
    validations:
      required: true

  - type: checkboxes
    id: precheck_redacted
    attributes:
      label: Privacy Check
      options:
        - label: I removed secrets (appSecret, tokens, cookies, etc.) from config/logs.
          required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Optional"
