name: "使用咨询（中文）"
description: "提问使用问题（建议附版本、配置和日志，便于排查）。"
title: "[Question] "
labels:
  - type:question
body:
  - type: markdown
    attributes:
      value: |
        该模板用于排查型咨询问题。
        提交前请先查看 Discussions 常见问答：https://github.com/m1heng/clawdbot-feishu/discussions

  - type: checkboxes
    id: precheck_search
    attributes:
      label: 提交前检查
      options:
        - label: 我已搜索 Discussions 和现有 issues，未找到可直接复用的答案。
          required: true

  - type: input
    id: openclaw_version
    attributes:
      label: OpenClaw 版本
      description: "例如：`openclaw --version` 输出"
      placeholder: "例如 2026.2.13"
    validations:
      required: true

  - type: input
    id: plugin_version
    attributes:
      label: 飞书插件版本
      description: "例如：`openclaw plugins list` 输出"
      placeholder: "例如 @m1heng-clawd/feishu <installed-version>"
    validations:
      required: true

  - type: dropdown
    id: setup_method
    attributes:
      label: 配置方式
      options:
        - "手工编辑 openclaw.json"
        - "通过 openclaw config set 命令"
        - "通过 onboarding 或 UI"
        - "混合方式"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 你的问题
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: 相关配置（可选）
      render: json

  - type: textarea
    id: logs
    attributes:
      label: 相关日志（可选）
      render: shell

  - type: checkboxes
    id: precheck_redacted
    attributes:
      label: 隐私检查
      options:
        - label: 我已移除配置和日志中的敏感信息（appSecret、token、cookie 等）。
          required: true
